config/routes.rb
PaybillSimulator::Application.routes.draw do
  resources :events

  root :to => "transactions#index"

  resources :transactions, :only => [:index, :show, :new, :create, :update, :destroy]

end

app/controllers/transactions_controller.rb
require 'rubygems'
require 'nokogiri'

class TransactionsController < ApplicationController

  def index
    @transactions = Transaction.all
    @Title = "All Transactions"

    respond_to do |format|
      format.html
      format.xml { render :xml => Transaction.build_all_xml }
    end
  end

  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html {redirect_to :action => 'index'}
      else
        format.html {render :action => 'new'}
      end
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
    @title = "Transaction information"
  end

  def update
    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        flash[notice] = "Successfully updated transaction."
        redirect to :index
      else
        render :action => 'index'
      end
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
<% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mp_transaction_id %><br />
    <%= f.text_field :mp_transaction_id %>
  </div>
  <div class="field">
    <%= f.label :biz_terminal_number %><br />
    <%= f.text_field :biz_terminal_number %>
  </div>
  <div class="field">
    <%= f.label :biller_business_number %><br />
    <%= f.text_field :biller_business_number %>
  </div>
  <div class="field">
    <%= f.label :transaction_date %><br />
    <%= f.date_select :transaction_date %>
  </div>
  <div class="field">
    <%= f.label :transaction_type %><br />
    <%= f.select('transaction_type', {'Paybill' => 'Paybill'}) %>
  </div>
  <div class="field">
    <%= f.label :account_number %><br />
    <%= f.text_field :account_number %>
  </div>
   <div class="field">
    <%= f.label :sender_msisdn %><br />
    <%= f.text_field :sender_msisdn %>
  </div>
  <div class="field">
    <%= f.label :sender_first_name %><br />
    <%= f.text_field :sender_first_name %>
  </div>
  <div class="field">
    <%= f.label :sender_middle_name %><br />
    <%= f.text_field :sender_middle_name %>
  </div>
  <div class="field">
    <%= f.label :sender_last_name %><br />
    <%= f.text_field :sender_last_name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table class="table">
<thead>
  <tr>
  <th>MP_TRANSACTION_ID</th>
  <th>BILLER_BUSINESS_NUMBER</th>
  <th>TRANSACTION_DATE</th>
  <th>TRANSACTION_TYPE</th>
  <th>ACCOUNT_NUMBER</th>
  <th>SENDER_MSISDN</th>
  <th>SENDER_FIRST_NAME</th>
  <th>SENDER_MIDDLE_NAME</th>
  <th>SENDER_LAST_NAME</th>
  <th>AMOUNT</th>
  <th>CURRENCY</th>
  <th>STATUS</th>
  </tr>
</thead>
<tfoot></tfoot>
<tbody>
<% @transactions.each do | transaction | %>
  <tr class="<%= cycle("even", "odd") %>">
    <td><%= transaction.mp_transaction_id %></td>
    <td><%= transaction.biller_business_number %></td>
    <td><%= transaction.transaction_date %></td>
    <td><%= transaction.type %></td>
    <td><%= transaction.account_number %></td>
    <td><%= transaction.sender_msisdn %></td>
    <td><%= transaction.sender_first_name %></td>
    <td><%= transaction.sender_middle_name %></td>
    <td><%= transaction.sender_last_name %></td>
    <td><%= transaction.amount %></td>
    <td><%= transaction.currency %></td>
    <td><%= transaction.status %></td>
  </tr>
<% end %>
</tbody>
</table>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>